name: flutter_naver_platform_interface
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ">=1.0.0 <3.0.0"
  # flutter_naver_map :
  #   git: 
  #     url : https://github.com/taeilyoon/flutter_naver_map.git
  #     path : flutter_naver_map
  flutter_naver_map :
     path : ../flutter_naver_map

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
